apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  VSPHERE_SERVER: {{ .Values.server.vsphereServer }}
  VSPHERE_USERNAME: {{ .Values.server.vsphereUsername }}
  VSPHERE_PASSWORD: {{ .Values.server.vspherePassword }}
  VSPHERE_DATACENTER: {{ .Values.server.vsphereDatacenter }}
  DB_HOST: {{ .Release.Name }}-cockroachdb-public